image: docker
services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  RELEASE_TAG: latest
  VERSION_TAG: $CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$VERSION_TAG .
    - docker push $CI_REGISTRY_IMAGE:$VERSION_TAG

deploy:
  stage: deploy
  image: docker:stable
  environment:
    name: production
    kubernetes:
      namespace: clockify-lp-int
  script:
    - apk add --no-cache curl bash openssl python3
    - curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-331.0.0-linux-x86_64.tar.gz
    - tar xzf google-cloud-sdk-331.0.0-linux-x86_64.tar.gz
    - export PATH="${PATH}:${PWD}/google-cloud-sdk/bin"
    - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - docker pull $CI_REGISTRY_IMAGE:$VERSION_TAG
    - docker tag $CI_REGISTRY_IMAGE:$VERSION_TAG $CI_REGISTRY_IMAGE:$RELEASE_TAG
    - docker push $CI_REGISTRY_IMAGE:$RELEASE_TAG
    - gcloud auth activate-service-account --key-file "${MISC_GCLOUD_SERVICE_ACCOUNT_KEY}"
    - gcloud container clusters get-credentials dev-cluster --zone australia-southeast1-a --project cluster-dev-294103
    - helm upgrade --install --wait --namespace=clockify-lp-int
      --set image.tag=$VERSION_TAG
      --set gitlab.app=$CI_PROJECT_PATH_SLUG
      --set gitlab.env=$CI_ENVIRONMENT_SLUG
      --set env.clockifyKey=$CLOCKIFY_API_KEY
      --set env.lpKey=$LP_API_KEY
      clockify-lp-int ./helm
  only:
    - main
