apiVersion: v1
kind: Service
metadata:
  name: {{ include "clockify-lp-int.fullname" . }}
  {{- if .Values.gitlab.enabled }}
  annotations:
    {{- include "clockify-lp-int.gitlab-annotations" . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "clockify-lp-int.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-node
      protocol: TCP
      name: http
  selector:
    {{- include "clockify-lp-int.selectorLabels" . | nindent 4 }}
