apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "clockify-lp-int.fullname" . }}
  {{- if .Values.gitlab.enabled }}
  annotations:
    {{- include "clockify-lp-int.gitlab-annotations" . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "clockify-lp-int.labels" . | nindent 4 }}
spec:
  gateways:
    - {{ include "clockify-lp-int.fullname" . }}
  hosts:
    - {{ .Values.ingress.host | quote }}
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: {{ include "clockify-lp-int.fullname" . }}
            port:
              number: {{ .Values.service.port }}